x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  image: custom-airflow:2.9.0-python3.9
  environment:
    &airflow-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__WEBSERVER__DEFAULT_USER_USERNAME: airflow
    AIRFLOW__WEBSERVER__DEFAULT_USER_PASSWORD: airflow
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
  depends_on:
    - postgres
  networks:
    - airflow_network

services:
  postgres:
    image: postgres:15
    container_name: airflow-postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - airflow_network

  airflow-init:
    <<: *airflow-common
    entrypoint: >
      bash -c "airflow db migrate &&
               airflow users create --username airflow --password airflow --firstname Airflow --lastname Admin --role Admin --email admin@example.com"

  webserver:
    <<: *airflow-common
    ports:
      - "8081:8080"
    command: webserver

  scheduler:
    <<: *airflow-common
    command: scheduler

volumes:
  postgres-db-volume:

networks:
  airflow_network:
    external: true